### ISSUE TITLE
Problem with install docker-py missing libssl, libcrypto

### ISSUE THREAD

**Issue by abtris** [defunctzombie/ansible-coreos-bootstrap#14]
```
core@ip-local ~ $ ./bin/pip install docker-py
/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
Collecting docker-py
  Could not find any downloads that satisfy the requirement docker-py
  No distributions at all found for docker-py
````

Any idea how solve this problem?

**Comment by abtris** [comment]
I can install adding ` --trusted-host pypi.python.org` but it's only hotfix.

**Comment by vidarh** [comment]
I'm seeing pretty much the same thing. This is on CoreOS 607. On older versions it works fine.

**Comment by brandonweiss** [comment]
Same :(

**Comment by brandonweiss** [comment]
Actually, mine might be different. It looks like docker-py is installing alright, but the next task is to run a docker container and I get:

```
failed: [192.241.211.202] => {"failed": true, "parsed": false}
/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/core/.ansible/tmp/ansible-tmp-1432055966.4-128553307475551/docker", line 3110, in <module>
    main()
  File "/home/core/.ansible/tmp/ansible-tmp-1432055966.4-128553307475551/docker", line 1449, in main
    manager = DockerManager(module)
  File "/home/core/.ansible/tmp/ansible-tmp-1432055966.4-128553307475551/docker", line 558, in __init__
    docker_api_version=docker.client.DEFAULT_DOCKER_API_VERSION
AttributeError: 'module' object has no attribute 'DEFAULT_DOCKER_API_VERSION'
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/brandon/.ssh/config
debug1: /Users/brandon/.ssh/config line 11: Applying options for *
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 192.241.211.202 closed.
```

Sorry, I'm totally new to Ansible and Docker. Is this also an issue with libssl and libcrypto?

**Comment by brandonweiss** [comment]
Nevermind, I just figured out I'd installed a newer, incompatible version of docker-py. Sorry!

**Comment by vse** [comment]
I have the same issue on CoreOS 681.2.0. What version worked for you @brandonweiss ?

**Comment by brandonweiss** [comment]
@vse I used `1.1.0`.

**Comment by mastertinner** [comment]
I'm still getting this issue... @brandonweiss, can you tell me what kind of tasks I have to run to get it to work? I'm running

```yml
- name: Install docker-py
  pip: name=docker-py version=1.1.0 executable=/home/core/pypy/bin/pip

- name: Start stack
  docker:
    image="nginx"
    name="example-nginx"
    ports="8080:80"
    state=running
```

and that's where it breaks with the error messages desribed above...

**Comment by brandonweiss** [comment]
Sorry, I stopped using Ansible completely—maybe the core of Ansible is really good, but every single module I tried to use was an absolute shit-show of bugs and non-existent documentation. I switched to using CoreOS's Fleet.

**Comment by mastertinner** [comment]
ok, thanks for the update

**Comment by mastertinner** [comment]
I've got it working now with the `docker` (https://docs.ansible.com/ansible/docker_module.html) module of Ansible. Unfortunately, the `docker_service` (https://docs.ansible.com/ansible/docker_service_module.html) one still throws the above error... @defunctzombie, do you have any advice?

**Comment by mastertinner** [comment]
Nevermind, I got it to work by simply installing Docker Compose using Pip:

```yml
- name: Start etcd
  service: name=etcd.service state=started

- name: Install docker-py
  pip: name=docker-py executable=/home/core/pypy/bin/pip

- name: Install docker-compose
  pip: name=docker-compose executable=/home/core/pypy/bin/pip
```
