### ISSUE TITLE
Problem run the playbook websit.yml

### ISSUE THREAD

**Issue by huikang** [defunctzombie/ansible-coreos-bootstrap#17]
Hi,
I go the following error when running  ansible-playbook  -i inventory/vagrant website.yml.

The step to install docker-py and pull the container imagess seem successful. It failed at launching the container. Can anyone help? Thanks.

My coreos version is VERSION=647.2.0

TASK: [pull container] ******************************************************** 
ok: [core-02]
ok: [core-01]

TASK: [launch nginx container] ************************************************ 
failed: [core-01] => {"failed": true, "parsed": false}
invalid output was: /home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/core/.ansible/tmp/ansible-tmp-1435675179.7-61095459323454/docker", line 1813, in <module>
    main()
  File "/home/core/.ansible/tmp/ansible-tmp-1435675179.7-61095459323454/docker", line 709, in main
    except docker.client.APIError, e:
AttributeError: 'module' object has no attribute 'APIError'

failed: [core-02] => {"failed": true, "parsed": false}
invalid output was: /home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/core/.ansible/tmp/ansible-tmp-1435675179.7-172731872346784/docker", line 1813, in <module>
    main()
  File "/home/core/.ansible/tmp/ansible-tmp-1435675179.7-172731872346784/docker", line 709, in main
    except docker.client.APIError, e:
AttributeError: 'module' object has no attribute 'APIError'

FATAL: all hosts have already failed -- aborting

**Comment by TooDizzy** [comment]
I see a similar error and it's kinda blocking. Any help is much appreciated.

**Comment by noqcks** [comment]
Same error here. 

coreos: 899.x
ansible: 2.1.0.0
